### ISSUE TITLE
Tournament Bracket Support

### ISSUE THREAD

**Issue by thordy** [kcapp/frontend#7]
• Tournament Bracket support
	- Need to support displaying proper brackets
	- Example International: https://challonge.com/trd_darts_2018, https://challonge.com/trd_darts_2017, https://challonge.com/trd_darts_2016, https://challonge.com/trd_darts_2015
	- Example League: See emails from Runar

**Comment by runarost** [comment]
Big and complex issue. Will be specified for next season.

**Comment by runarost** [comment]
Should support both league playoffs format, and possibly also international qualifier format.

**Comment by runarost** [comment]
Stuff done to support brackets in Preview page shows that we're on the right track.

**Comment by runarost** [comment]
Some of the things that can be improved:
- Cleanup of old seasons.
- Of particular mention, currently there is a PlayerA vs. PlayerB match in Spring 2018 because there's no support yet for custom playoffs format depending on number of players (only 8 players in Conference, so no Prelimination Final).

**Comment by runarost** [comment]
Don't show score "0-0" if match is unplayed

**Comment by runarost** [comment]
In addition to fixing the things mentioned above (of which the 0-0 is probably the most important), we also discussed during sprint planning whether we should have a specific W.O. notice to signal which matches that weren't actually played.
