### ISSUE TITLE
Add support for 9 Dart Shootout ending in Draw

### ISSUE THREAD

**Issue by thordy** [kcapp/frontend#9]
Currently if a 9 dart shootout match ends in a draw, the behavior is undefined

**Comment by Chmieloo** [comment]
(second player wins)

**Comment by runarost** [comment]
I'm not sure what they use officially, but I would be very surprised if there was something other than one more visit or three more visits per player ad infinitum until there's a difference in score.

At least I personally suggest we do one more visit until there's a clear ranking for all players.

I would also take care to ensure that in these cases, rankings should be done not on `totalScore`, because that would mess up when the following scenario:

| Player | Visit 1 | Visit 2 | Visit 3 | Visit 4 | Visit 5
|--------|---------|---------|---------|---------|---------|
| A      | 60      | 60      | 60      |         |         |
| B      | 60      | 60      | 45      | 60      | 60      | 
| C      | 60      | 60      | 45      | 60      | 55      |

Rank by score after 3rd visit, then 4th visit, etc.

**Comment by thordy** [comment]
This has been solved for matches with 2 players
